### ISSUE TITLE
你好,你的这个项目并没有说明怎么用呀,能否写个使用说明呢

### ISSUE THREAD

**Issue by fenggehua** [yu45020/Waifu2x#4]
你好,你的这个项目并没有说明怎么用呀,能否写个使用说明呢

**Comment by yu45020** [comment]
抱歉抱歉，一开始完全是用来做pytorch练手的。 感谢你的关注。 周末的时候会抽空补完。

**Comment by yu45020** [comment]
@fenggehua 

主页已更新，请配合[这里](https://github.com/yu45020/Waifu2x/tree/master/model_check_points/CRAN_V2) ，[这里](https://github.com/yu45020/Waifu2x#how-to-use) 食用。
